import { useEffect, useMemo } from 'react';
import Slide from './Slide.jsx';
const fmt=n=>Number(n||0).toLocaleString(); const pct=(n,d)=>d?Math.round(n/d*100):0; const date=d=>d?new Date(d).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—'; const hour=h=>`${h%12||12}${h<12?' AM':' PM'}`;

export default function Deck({stats,index,onPrev,onNext,onGo,onReset}){
 const maxHour=Math.max(...stats.hours.map(x=>x.count),1),maxAuthor=Math.max(...stats.authors.map(x=>x.count),1);
 const slides=useMemo(()=>[
  <><div className="slide-kicker"><span>01</span> OVERVIEW</div><div className="hero">{fmt(stats.total)}</div><h2>messages that became<br/><em>a story.</em></h2><div className="insight-line"><span>{stats.activeDays} active days</span><i/> <span>{stats.spanDays} days covered</span></div></>,
  <><div className="slide-kicker"><span>02</span> PEOPLE</div><h2>Every great chat<br/><em>has a cast.</em></h2><div className="rank-list">{stats.authors.map((a,i)=><div className="rank" key={a.name}><b>0{i+1}</b><span className="rank-name">{a.name}</span><div className="bar-track"><div className="bar" style={{width:`${pct(a.count,maxAuthor)}%`}}/></div><strong>{fmt(a.count)}</strong></div>)}</div></>,
  <><div className="slide-kicker"><span>03</span> PEAK TIME</div><div className="metric">{hour(stats.peakHour)}</div><h2>when the chat<br/><em>comes alive.</em></h2><div className="hour-chart">{stats.hours.map(x=><div className="hour" key={x.name} title={`${hour(x.name)} · ${x.count} messages`}><div className="hour-bar" style={{height:`${Math.max(3,x.count/maxHour*100)}%`}}/><span>{x.name}</span></div>)}</div></>,
  <><div className="slide-kicker"><span>04</span> RHYTHM</div><h2>There is a pattern<br/><em>to your presence.</em></h2><div className="stat-grid">{stats.weekdays.map(x=><div className="stat" key={x.name}><strong>{fmt(x.count)}</strong><span>{x.name}</span></div>)}</div><p className="muted">Average {fmt(stats.avgPerActiveDay)} messages per active day.</p></>,
  <><div className="slide-kicker"><span>05</span> BIGGEST DAY</div><div className="hero">{fmt(stats.busiestDay?.count)}</div><h2>messages.<br/><em>one unforgettable day.</em></h2><p className="muted">{stats.busiestDay?.day||'No date available'}</p></>,
  <><div className="slide-kicker"><span>06</span> THE PAUSE</div><div className="metric">{stats.longestSilence?.hours||0}<small>h</small></div><h2>the longest silence<br/><em>between words.</em></h2><p className="muted">Last message before the gap: {date(stats.longestSilence?.at)}</p></>,
  <><div className="slide-kicker"><span>07</span> EMOJI DNA</div><div className="emoji">{stats.topEmoji}</div><h2>One tiny symbol<br/><em>says a lot.</em></h2><div className="emoji-row">{stats.emojis.map(x=><span key={x.name}>{x.name} <small>{x.count}</small></span>)}</div></>,
  <><div className="slide-kicker"><span>08</span> VOCABULARY</div><h2>The words that<br/><em>sound like you.</em></h2><div className="word-cloud">{stats.topWords.map((x,i)=><span key={x.name} style={{fontSize:`${1+(i%4)*.25}rem`}}>{x.name} <small>{x.count}</small></span>)}</div></>,
  <><div className="slide-kicker"><span>09</span> OPENERS</div><h2>Who starts<br/><em>the story?</em></h2>{stats.openers.map(x=><div className="bar-row" key={x.name}><span>{x.name}</span><div className="bar-track"><div className="bar" style={{width:`${pct(x.count,stats.openers[0]?.count||1)}%`}}/></div><b>{x.count}</b></div>)}</>,
  <><div className="slide-kicker"><span>10</span> CONNECTION</div><div className="metric">{stats.response?.averageMinutes||0}<small> min</small></div><h2>average reply time.</h2><p className="muted">Based on {fmt(stats.response?.samples||0)} cross-person message pairs within 24 hours.</p></>,
  <><div className="slide-kicker"><span>11</span> THE FINALE</div><div className="hero">{fmt(stats.mediaCount)}</div><h2>memories attached<br/><em>to the conversation.</em></h2><p className="muted">From {date(stats.first)} to {date(stats.last)}.</p><button className="finish-cta" onClick={onReset}>Analyse another chat <span>↗</span></button></>
 ],[stats,maxHour,maxAuthor,onReset]);
 useEffect(()=>{const key=e=>{if(e.key==='ArrowRight'||e.key===' '){e.preventDefault();if(index<slides.length-1)onNext(slides.length)}if(e.key==='ArrowLeft'&&index>0)onPrev();if(e.key==='Home')onReset()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index,slides.length,onNext,onPrev,onReset]);
 return <div className="deck"><div className="deck-glow"/><div className="topbar"><strong><span>◈</span> CHAT WRAPPED</strong><span>{String(index+1).padStart(2,'0')} <i>/</i> {String(slides.length).padStart(2,'0')}</span></div><div className="progress"><i style={{width:`${(index+1)/slides.length*100}%`}}/></div><Slide key={index}>{slides[index]}</Slide><div className="controls"><button className="nav" onClick={onPrev} disabled={!index}>←</button><div className="dots" aria-label="Story progress">{slides.map((_,i)=><button key={i} aria-label={`Go to slide ${i+1}`} className={i===index?'dot active':'dot'} onClick={()=>onGo(i,slides.length)}/>)}</div><button className="nav" onClick={()=>onNext(slides.length)} disabled={index===slides.length-1}>→</button></div><p className="privacy footer-note">LOCAL PROCESSING · YOUR DATA NEVER LEAVES THIS DEVICE</p></div>;
}
